### ISSUE TITLE
Docx dosya uzantısı

### ISSUE THREAD

**Issue by volkansahin45** [merve-bulut/Yazilim-Kalitesi#1]
Dökümanı pdf olarak export edip yüklersen web arayüzü üzerinden de görüntüleme sağlayabilirsin. Okumak için indirmek zorunda kalınmaz.
Ayrıca docx farklı office uygulamaları ve versiyonlarında bazı stil bozukluklarına yol açabilir.

**Comment by merve-bulut** [comment]
Ben pdf uzantısını yükledim sanıyordum, uyarınız için teşekkür ederim. En
kısa zamanda düzelteceğim. Sağlıcakla kalın!
